name: Deployment Using Kubectl
on:
  workflow_call:
    inputs:
      NAMESPACE:
        description: "Kubernetes Namespace to deploy the application"
        required: true
        type: string
      IMAGE_NAME:
        description: "Docker Image Name without Tag"
        required: true
        type: string
      IMAGE_TAG:          # ← add this
        required: true
        type: string
    secrets:
      KUBECONFIG:
        description: "KubeConfig file content for accessing the Kubernetes Cluster"
        required: true
jobs:
  deploy:
        env:
            NAMESPACE: ${{ inputs.NAMESPACE }}
        # needs: ci-pipeline-job
        runs-on: github-actions-scaleset-demo
        steps:
          - name: Checkout code Reository
            uses: actions/checkout@v6.0.3
          - name: Install kubectl
            run: |
              curl --proto '=https' --tlsv1.2 -LO "https://dl.k8s.io/release/$(curl --proto '=https' --tlsv1.2 -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
              chmod +x ./kubectl
              sudo mv ./kubectl /usr/local/bin/kubectl
              kubectl version --client
          - name: Configure kubeconfig
            run: |
              mkdir -p ~/.kube
              echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
              kubectl version
              kubectl get nodes
          - name: Install yq
            run: |
              sudo curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
              sudo chmod +x /usr/local/bin/yq
              yq --version
          - name: Update Image name in deployment.yml
            run: |
              export IMAGE="${{ inputs.IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}"
              yq e '.spec.template.spec.containers[0].image = strenv(IMAGE)' manifests/deployment.yml -i
              cat manifests/deployment.yml

          - name: Create Namespace if not exist
            run: |
              kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE
          - name: Deploy to Kubernetes Cluster
            run: |
              kubectl apply -f manifests/ -n $NAMESPACE
          - name: Verify Deployment
            run: |
              kubectl rollout status deployment/sajjadathar-deployment -n $NAMESPACE
              kubectl get all -n $NAMESPACE
